name: XLINXCHAT
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:

  cupertino_icons: ^1.0.2

  # api calling
  http: ^0.13.3

  # MMVM architecture
  stacked: ^2.1.8

  # state management
  get: ^4.1.4
  rxdart: ^0.27.1

  build_runner: ^1.10.11
  record: ^3.0.0
  adhara_socket_io: ^1.0.1+1
  socket_io_client: ^1.0.1
  # firebase
  firebase_core: ^1.3.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  audioplayers: ^0.7.8
  device_info: ^2.0.3
  provider: ^5.0.0
  local_auth: ^1.1.0
  otp_text_field: ^1.0.2

  # local push notification
  flutter_local_notifications: ^6.0.0
  # screen & app util
  flutter_screenutil: ^5.0.0+2
  intl: ^0.17.0

  # image & doc picker
  image_picker: ^0.8.0+3
  file_picker: ^3.0.3

  # path prover
  path_provider: ^0.4.1

  # permission handler
  permission_handler: ^8.1.1
  audio_recorder: ^1.0.2
  file: ^5.0.4

  # open file from chat
  open_file: ^3.2.1

  # download and cache image
  agora_rtc_engine: ^4.0.2

  # generate http link and launch
  flutter_linkify: ^5.0.2
  url_launcher: ^6.0.7
  shared_preferences: ^0.5.6+1
  flutter_svg: ^0.19.0

  # chat pagination
  paginate_firestore: ^1.0.1

dev_dependencies:
  audio_recorder:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Bold.ttf
        - asset: assets/font/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/font/Nunito-Regular.ttf
        - asset: assets/font/Nunito-SemiBold.ttf
          weight: 500

    - family: Mulish
      fonts:
        - asset: assets/font/mulish/Mulish-Regular.ttf